[package]
name = "flac-sysmonitor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
sysinfo = "0.29.0"
hound = "3.5"
chrono = "*"
claxon = "*"
prometheus = "*"
warp = "*"
tokio = { version= "1", features = ["full"] }
futures="*"
symphonia= { version = "*", features = ["flac"] } 
prom-remote-api = { version = "0.2.2", features=["warp"]}
async-trait = "*"
env_logger = "0.10.0"
log = "0.4.0"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
codegen-units = 1