[package]
name = "flac-sysmonitor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
sysinfo = "0.29.0"

[dependencies]
sysinfo = "0.29.0"
hound = "*"
chrono = "*"
claxon = "*"
prometheus = "*"
warp = "*"
tokio = { version= "1", features = ["full"] }
futures="*"